# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-24 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quiz', models.SmallIntegerField()),
            ],
        ),
    ]
